//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Logmessage { get; set; }
        public string Session { get; set; }
        public string UserIpAddress { get; set; }
        public string Browser { get; set; }
    }
}
