//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppTask
    {
        public int TaskId { get; set; }
        public string TaskTypeId { get; set; }
        public string TaskTable { get; set; }
        public string TaskPrimaryKey { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Pririoty { get; set; }
        public Nullable<int> Retry { get; set; }
        public string TaskBody { get; set; }
    }
}
