//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int ID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string CardHolderName { get; set; }
        public string CardNo { get; set; }
        public string SecurityCode { get; set; }
        public string ExpiryDate { get; set; }
    
        public virtual CreditCard CreditCard1 { get; set; }
        public virtual CreditCard CreditCard2 { get; set; }
    }
}
