//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAttachment
    {
        public int EmailDataAttachmentId { get; set; }
        public int EmailID { get; set; }
        public string AttachmedName { get; set; }
        public string AttachmentFullPath { get; set; }
        public Nullable<bool> IsAttachmentEncripted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
