//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class eMenu_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eMenu_Master()
        {
            this.RoleMenuMappings = new HashSet<RoleMenuMapping>();
        }
    
        public int nMenuID { get; set; }
        public string strPageName { get; set; }
        public int nParentID { get; set; }
        public string strPagePath { get; set; }
        public string strImagePath { get; set; }
        public Nullable<bool> bIsPermission { get; set; }
        public Nullable<int> nOrder { get; set; }
        public Nullable<System.DateTime> dtAddDate { get; set; }
        public Nullable<int> nAddBy { get; set; }
        public Nullable<System.DateTime> dtUpdateDate { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtDeleteDate { get; set; }
        public Nullable<int> nDeleteBy { get; set; }
        public Nullable<bool> bIsDeleted { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleMenuMapping> RoleMenuMappings { get; set; }
    }
}
