//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDCPermit
    {
        public int PermitTypelinkID { get; set; }
        public Nullable<int> ApplyLocationID { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string PackageType { get; set; }
        public string PackageCount { get; set; }
        public string PackageWeight { get; set; }
        public string PackageWeightUnit { get; set; }
        public string DestructionReason { get; set; }
        public string InspectionForm { get; set; }
        public string FacilityLocation { get; set; }
        public Nullable<int> PermitId { get; set; }
        public string CountryOfOrigin { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
