//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HazardContractItem
    {
        public int ID { get; set; }
        public int PermitID { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public string State { get; set; }
        public string ContainerType { get; set; }
        public string QuantityItem { get; set; }
    }
}
