//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalPermit
    {
        public int PermitTypelinkID { get; set; }
        public Nullable<int> WasteCategory { get; set; }
        public Nullable<int> WasteType { get; set; }
        public string WasteLocation { get; set; }
        public string SourceProcess { get; set; }
        public string PackagingStorage { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PermitId { get; set; }
    }
}
