//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermitRequest()
        {
            this.AccountTransactions = new HashSet<AccountTransaction>();
            this.Invoices = new HashSet<Invoice>();
            this.SamplingRequests = new HashSet<SamplingRequest>();
            this.PermitItems = new HashSet<PermitItem>();
        }
    
        public int ID { get; set; }
        public bool PermitType { get; set; }
        public Nullable<int> PermitReferenceID { get; set; }
        public string TotalWeight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<bool> IsSamplingRequired { get; set; }
        public Nullable<int> PurposeOfSampling { get; set; }
        public Nullable<int> SourceOfSample { get; set; }
        public string Othersource { get; set; }
        public Nullable<bool> IsPaymentDone { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> IssueBy { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public Nullable<int> ApproveBy { get; set; }
        public Nullable<int> UserID { get; set; }
        public string WasteGenerationDescription { get; set; }
        public string FrequencyOfDisposal { get; set; }
        public string Transporter { get; set; }
        public string ApplicantName { get; set; }
        public bool IsRead { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Industry { get; set; }
        public string HazardSAP { get; set; }
        public string HazardRemarks { get; set; }
        public string HazardTransporter { get; set; }
        public string WBRemarks { get; set; }
        public string ConsumedWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual PurposeOfSamplingMaster PurposeOfSamplingMaster { get; set; }
        public virtual SourceOfSampleMaster SourceOfSampleMaster { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SamplingRequest> SamplingRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermitItem> PermitItems { get; set; }
    }
}
