//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusMaster()
        {
            this.PermitRequests = new HashSet<PermitRequest>();
        }
    
        public int ID { get; set; }
        public string statusName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> status { get; set; }
        public string UserEmailFileLink { get; set; }
        public string ClientEmailFileLink { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string ReceiverRoles { get; set; }
        public string UserEmailBody { get; set; }
        public string ClientEmailBody { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermitRequest> PermitRequests { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
