//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFZMVC.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WasteManageEntities : DbContext
    {
        public WasteManageEntities()
            : base("name=WasteManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<EmailAttachment> EmailAttachments { get; set; }
        public virtual DbSet<eMenu_Master> eMenu_Master { get; set; }
        public virtual DbSet<FDCPermit> FDCPermits { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<MasterItem> MasterItems { get; set; }
        public virtual DbSet<NormalPermit> NormalPermits { get; set; }
        public virtual DbSet<PurposeOfSamplingMaster> PurposeOfSamplingMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<RoleMenuMapping> RoleMenuMappings { get; set; }
        public virtual DbSet<SourceOfSampleMaster> SourceOfSampleMasters { get; set; }
        public virtual DbSet<UserRoleMapping> UserRoleMappings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CreditCard> CreditCards { get; set; }
        public virtual DbSet<AccountTransaction> AccountTransactions { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<AppLog> AppLogs { get; set; }
        public virtual DbSet<ClientDocumentDetail> ClientDocumentDetails { get; set; }
        public virtual DbSet<DocumentTypeMaster> DocumentTypeMasters { get; set; }
        public virtual DbSet<PermitWasteMapping> PermitWasteMappings { get; set; }
        public virtual DbSet<PermitTypeMaster> PermitTypeMasters { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<PackagingStorageMaster> PackagingStorageMasters { get; set; }
        public virtual DbSet<PermitDocumentDetail> PermitDocumentDetails { get; set; }
        public virtual DbSet<PermitRequest> PermitRequests { get; set; }
        public virtual DbSet<SamplingRequest> SamplingRequests { get; set; }
        public virtual DbSet<StatusMaster> StatusMasters { get; set; }
        public virtual DbSet<PermitItem> PermitItems { get; set; }
        public virtual DbSet<HazardContractItem> HazardContractItems { get; set; }
        public virtual DbSet<AppTask> AppTasks { get; set; }
    }
}
