    <footer class="footer">Copyrights © 2019, Beeah. All Rights Reserved.</footer>
        </div>
        <!-- ============================================================== -->
        <!-- End Right content here -->
        <!-- ============================================================== -->
    </div>

<div class="locationmap">
	<div class="locationmap-overlay"></div>
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3606.091745298663!2d55.38640191568766!3d25.33470223232379!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f5bc39be63cf1%3A0xfecbbba84b50be74!2sBee&#39;ah%20Head%20Office!5e0!3m2!1sen!2sae!4v1573505133582!5m2!1sen!2sae" width="80%" height="80%" frameborder="0" allowfullscreen=""></iframe>
	<div class="savelocation">Save Location</div>
	<div class="locationmap-close">&times;</div>
</div>
    <!-- END wrapper -->
    <!-- jQuery  -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/metisMenu.min.js"></script>
    <script src="assets/js/jquery.slimscroll.js"></script>
    <script src="assets/js/waves.min.js"></script>
    <script src="../plugins/jquery-sparkline/jquery.sparkline.min.js"></script>
    <!-- Required datatable js -->
    <script src="../plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="../plugins/datatables/dataTables.bootstrap4.min.js"></script>
    <!-- Buttons examples -->
    <script src="../plugins/datatables/dataTables.buttons.min.js"></script>
    <script src="../plugins/datatables/buttons.bootstrap4.min.js"></script>
    <script src="../plugins/datatables/jszip.min.js"></script>
    <script src="../plugins/datatables/pdfmake.min.js"></script>
    <script src="../plugins/datatables/vfs_fonts.js"></script>
    <script src="../plugins/datatables/buttons.html5.min.js"></script>
    <script src="../plugins/datatables/buttons.print.min.js"></script>
    <script src="../plugins/datatables/buttons.colVis.min.js"></script>
    <!--Morris Chart-->
    <script src="../plugins/morris/morris.min.js"></script>
    <script src="../plugins/raphael/raphael-min.js"></script>
    <script src="assets/pages/dashboard.js"></script>
    <!-- App js -->
    <!-- Datatable init js -->
    <script src="assets/pages/datatables.init.js"></script>
    <script src="assets/js/jquery.smartWizard.js"></script>
    <!-- App js -->
    <script src="assets/js/app.js"></script>

    <script src="assets/js/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-3d.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>

<script src="assets/pages/form-advanced.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
          $('#smartwizard').smartWizard({
            theme: 'circles',
            });

          Highcharts.chart('threedChart', {

  chart: {
    type: 'column'
  },

  title: {
    text: 'Total permits generated by companies'
  },

  xAxis: {
    categories: ['Type1', 'Type2', 'Type3', 'Type4', 'Type5']
  },

  yAxis: {
    allowDecimals: false,
    min: 0,
    title: {
      text: 'Number of permits'
    }
  },

  tooltip: {
    formatter: function () {
      return '<b>' + this.x + '</b><br/>' +
        this.series.name + ': ' + this.y + '<br/>' +
        'Total: ' + this.point.stackTotal;
    }
  },

  plotOptions: {
    column: {
      stacking: 'normal'
    }
  },

  series: [{
    name: 'Company1',
    data: [5, 3, 4, 7, 2],
    stack: 'Waste'
  }, {
    name: 'Company2',
    data: [3, 4, 4, 2, 5],
    stack: 'Food'
  }, {
    name: 'Company3',
    data: [2, 5, 6, 2, 1],
    stack: 'Waste'
  }, {
    name: 'Company4',
    data: [3, 0, 4, 4, 3],
    stack: 'Food'
  }]
});
        });
    </script>
<script>
$(document).ready(function(){
  $(".companyinfo-next").click(function(){
    $(".wastedescription-div").show();
    $(".companyinfo-div").hide();
    $(".waste-description").removeClass('deactiveprogress');
    $(".waste-description").addClass('activeprogress');
    $(".no-one").hide();
    $(".no-two").show();

  });

  $(".wastedescription-prev").click(function(){
    $(".wastedescription-div").hide();
    $(".companyinfo-div").show();
    $(".waste-description").addClass('deactiveprogress');
    $(".waste-description").removeClass('activeprogress');
    $(".no-one").show();
    $(".no-two").hide();

  });

  $(".wastedescription-next").click(function(){
    $(".purposesample-div").show();
    $(".wastedescription-div").hide();
    $(".purpose-sampling").removeClass('deactiveprogress');
    $(".purpose-sampling").addClass('activeprogress');
    $(".no-two").hide();
    $(".no-three").show();
  });
    
  $(".purposesample-prev").click(function(){
    $(".purposesample-div").hide();
    $(".wastedescription-div").show();
    $(".purpose-sampling").addClass('deactiveprogress');
    $(".purpose-sampling").removeClass('activeprogress');
    $(".no-three").hide();
    $(".no-two").show();
  });

  $(".purposesample-next").click(function(){
    $(".disclaimer-div").show();
    $(".purposesample-div").hide();
    $(".disclaimer").removeClass('deactiveprogress');
    $(".disclaimer").addClass('activeprogress');
    $(".no-three").hide();
    $(".no-four").show();
  });

  $(".disclaimer-prev").click(function(){
    $(".disclaimer-div").hide();
    $(".purposesample-div").show();
    $(".disclaimer").addClass('deactiveprogress');
    $(".disclaimer").removeClass('activeprogress');
    $(".no-four").hide();
    $(".no-three").show();
  });

   $(".checkoutbtn").click(function(){
    $("#smartwizard").hide();
    $(".creditcard").show();
  });
   
   $(".cancelcheckout").click(function(){
    $("#smartwizard").show();
    $(".creditcard").hide();
  });

       $(".openthemap").click(function(){
    $(".detectlocation").toggle();
  });

$(".dataTables_filter input").attr("placeholder", "Search");
	
	$(".addaddress-btn").click(function(){
		$(".addaddres-form").show();
		$(".add-address-btn").hide();
		$(".addaddres-saved").hide();
	});

	$(".savenew-address").click(function(){
		$(".addaddres-saved").show();
		$(".add-address-btn").show();
		$(".addaddres-form").hide();
	});

	$(".locationmap-close").click(function(){
		$(".locationmap").hide();
	});
	$(".openlocationmap").click(function(){
		$(".locationmap").show();
	});
	
	$(".tabcircle").click(function(){
		$(".tabcircle").removeClass("active");
		$(this).addClass("active");
	});

});
</script>
<script>
function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>

  <script>
$(document).ready(function(){
    $('input[type="radio"]').click(function(){
        var inputValue = $(this).attr("value");
        var targetBox = $("." + inputValue);
        $(".box").not(targetBox).hide();
        $(targetBox).show();
    });
});
</script>

<script>
	
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>

</body>

</html>